/**
 * LCG — Las Cosas Que Me Gustan
 * Catálogo real, cargado desde la cuenta de WhatsApp Business de LCG (colección
 * "Especial Día Del Niño") el 31/07/2026. Nombres, precios, medidas, materiales
 * y fotos son los publicados por LCG en ese momento.
 *
 * Nota: este es un catálogo chico y estacional. Los productos descriptos en el
 * resto del sitio (tarjetas, toppers, papelería para emprendimientos/repostería)
 * todavía no tienen carga real — quedan como categorías vacías hasta que se
 * sincronice más catálogo desde WhatsApp Business.
 *
 * En una implementación definitiva, este archivo debería reemplazarse por datos
 * provenientes de un backend / CMS / planilla conectada, no hardcodeados.
 */
const LCG_PRODUCTS = [
  {
    id: "washi-01",
    slug: "washi-tapes-feliz-dia",
    name: "Washi Tapes x 20 u.",
    category: "stickers",
    categoryLabel: "Stickers y Washi Tapes",
    occasion: ["cumpleanos"],
    pack: "Pack x 20 unidades",
    price: 2900,
    stock: "in_stock",
    badges: ["new"],
    personalizable: false,
    measures: "6 cm aprox. de ancho",
    material: "Autoadhesivo brillante de 115 g",
    finish: "Impresión digital, terminación brillante",
    productionTime: "3 a 5 días hábiles",
    minQty: 20,
    description: "20 washi tapes con estampado “¡Feliz Día!”, ideales para decorar tarjetas, regalos y manualidades. Impresas en autoadhesivo brillante de 115 g.",
    images: ["assets/productos/washi-tapes-1.jpg", "assets/productos/washi-tapes-2.jpg"],
    related: ["stk-superheroes", "etq-mini"],
  },
  {
    id: "stk-superheroes",
    slug: "set-stickers-superheroes",
    name: "Set de Stickers x 2 (36 stickers)",
    category: "stickers",
    categoryLabel: "Stickers y Washi Tapes",
    occasion: ["cumpleanos"],
    pack: "Pack x 2 planchas / 36 stickers",
    price: 2900,
    stock: "in_stock",
    badges: ["new", "most_picked"],
    personalizable: false,
    measures: "17 x 13 cm aprox. por plancha",
    material: "Autoadhesivo brillante de 115 g",
    finish: "Impresión digital, terminación brillante",
    productionTime: "3 a 5 días hábiles",
    minQty: 2,
    description: "Set de 2 planchas con 36 stickers de superhéroes para decorar todo: cuadernos, regalos y celebraciones infantiles.",
    images: ["assets/productos/stickers-superheroes-1.jpg", "assets/productos/stickers-superheroes-2.jpg"],
    related: ["washi-01", "tag-zorrito"],
  },
  {
    id: "etq-maxi",
    slug: "maxi-etiquetas-mini-heroes",
    name: "Maxi Etiquetas x 8 u.",
    category: "etiquetas",
    categoryLabel: "Etiquetas personalizadas",
    occasion: ["cumpleanos"],
    pack: "Pack x 8 unidades",
    price: 3500,
    stock: "in_stock",
    badges: ["most_picked"],
    personalizable: true,
    measures: "17 x 6 cm aprox.",
    material: "Autoadhesivo brillante de 115 g",
    finish: "Impresión digital brillante",
    productionTime: "3 a 5 días hábiles",
    minQty: 8,
    description: "8 maxi etiquetas “Mini Héroes”, personalizadas con tu cuenta de Instagram, marca o nombre. Impresas en autoadhesivo brillante de 115 g.",
    customFields: ["Cuenta de Instagram", "Marca o nombre"],
    images: ["assets/productos/maxi-etiquetas-1.jpg"],
    related: ["etq-mini", "washi-01"],
  },
  {
    id: "etq-mini",
    slug: "etiquetas-mini-super-heroes",
    name: "Etiquetas Mini Súper Héroes x 15 u.",
    category: "etiquetas",
    categoryLabel: "Etiquetas personalizadas",
    occasion: ["cumpleanos"],
    pack: "Pack x 15 unidades",
    price: 3500,
    stock: "in_stock",
    badges: ["new"],
    personalizable: true,
    measures: "4 x 10 cm aprox.",
    material: "Autoadhesivo brillante de 115 g",
    finish: "Impresión digital brillante",
    productionTime: "3 a 5 días hábiles",
    minQty: 15,
    description: "15 etiquetas “mini súper héroes”, personalizadas con tu cuenta de Instagram, marca o nombre. El personaje ilustrado puede variar según el stock disponible.",
    customFields: ["Cuenta de Instagram", "Marca o nombre"],
    images: ["assets/productos/etiquetas-mini-heroes-1.jpg", "assets/productos/etiquetas-mini-heroes-2.jpg"],
    related: ["etq-maxi", "stk-superheroes"],
  },
  {
    id: "tag-zorrito",
    slug: "tag-super-zorrito",
    name: "Tag Super Zorrito x 15 u.",
    category: "tags",
    categoryLabel: "Tags y mini tags",
    occasion: ["cumpleanos"],
    pack: "Pack x 15 tags dobles + 15 mini rayitos 3D",
    price: 9900,
    stock: "in_stock",
    badges: ["most_picked"],
    personalizable: true,
    measures: "9,5 x 5 cm aprox. (mini rayito 3D: 2x2 cm aprox.)",
    material: "Cartulina + mini figura 3D impresa en PLA amarillo",
    finish: "Tag doble con cordón + mini figura 3D",
    productionTime: "5 a 7 días hábiles",
    minQty: 15,
    description: "15 tags dobles “Zorrito”, personalizados con tu cuenta de Instagram, marca o nombre, más 15 mini rayitos impresos en 3D (PLA amarillo).",
    customFields: ["Cuenta de Instagram", "Marca o nombre"],
    images: ["assets/productos/tag-zorrito-1.jpg", "assets/productos/tag-zorrito-2.jpg"],
    related: ["tag-conejita", "stk-superheroes"],
  },
  {
    id: "tag-conejita",
    slug: "tag-super-conejita",
    name: "Tag Super Conejita x 15 u.",
    category: "tags",
    categoryLabel: "Tags y mini tags",
    occasion: ["cumpleanos"],
    pack: "Pack x 15 tags dobles + 15 mini estrellitas 3D",
    price: 9900,
    stock: "in_stock",
    badges: ["new", "most_picked"],
    personalizable: true,
    measures: "9,5 x 5 cm aprox. (mini estrellita 3D: 2x2 cm aprox.)",
    material: "Cartulina + mini figura 3D impresa en PLA amarillo",
    finish: "Tag doble con cordón + mini figura 3D",
    productionTime: "5 a 7 días hábiles",
    minQty: 15,
    description: "15 tags dobles “Conejita”, personalizados con tu cuenta de Instagram, marca o nombre, más 15 mini estrellitas impresas en 3D (PLA amarillo).",
    customFields: ["Cuenta de Instagram", "Marca o nombre"],
    images: ["assets/productos/tag-conejita-1.jpg", "assets/productos/tag-conejita-2.jpg"],
    related: ["tag-zorrito", "etq-maxi"],
  },
  {
    id: "tarjeton-pandita",
    slug: "tarjeton-super-pandita",
    name: "Tarjetón Super Pandita x 12 u.",
    category: "tarjetas",
    categoryLabel: "Tarjetas",
    occasion: ["cumpleanos"],
    pack: "Pack x 12 unidades",
    price: 6000,
    stock: "in_stock",
    badges: ["new"],
    personalizable: true,
    measures: "10 x 10 cm aprox.",
    material: "Papel fotográfico mate 220 g",
    finish: "Consultar",
    productionTime: "Consultar",
    minQty: 12,
    description: "12 tarjetones “Súper Pandita”, personalizados con tu cuenta de Instagram, marca o nombre.",
    customFields: ["Cuenta de Instagram", "Marca o nombre"],
    images: ["assets/productos/tarjeton-pandita-1.jpg", "assets/productos/tarjeton-pandita-2.jpg"],
    related: ["tarjeton-raton", "tag-conejita"],
  },
  {
    id: "tarjeton-raton",
    slug: "tarjeton-super-raton",
    name: "Tarjetón Super Ratón x 12 u.",
    category: "tarjetas",
    categoryLabel: "Tarjetas",
    occasion: ["cumpleanos"],
    pack: "Pack x 12 unidades",
    price: 6000,
    stock: "in_stock",
    badges: ["new"],
    personalizable: true,
    measures: "10 x 10 cm aprox.",
    material: "Papel fotográfico mate 220 g",
    finish: "Consultar",
    productionTime: "Consultar",
    minQty: 12,
    description: "12 tarjetones “Súper Ratón”, personalizados con tu cuenta de Instagram, marca o nombre.",
    customFields: ["Cuenta de Instagram", "Marca o nombre"],
    images: ["assets/productos/tarjeton-raton-1.jpg", "assets/productos/tarjeton-raton-2.jpg"],
    related: ["tarjeton-pandita", "tag-zorrito"],
  },
  {
    id: "tag-doble-dije",
    slug: "tag-doble-con-dije",
    name: "Tag Doble con Dije",
    category: "tags",
    categoryLabel: "Tags y mini tags",
    occasion: ["cumpleanos"],
    pack: "Consultar",
    price: null,
    priceOnRequest: true,
    stock: "on_request",
    badges: ["new"],
    personalizable: true,
    measures: "Consultar",
    material: "Consultar",
    finish: "Tag doble con cordón y dije colgante",
    productionTime: "Consultar",
    minQty: "Consultar",
    description: "Tags dobles “Feliz Día” con dije colgante a juego. Foto real cargada el 01/08/2026; precio, medidas y tiempos de producción a confirmar — escribinos por WhatsApp.",
    images: ["assets/productos/tag-doble-dije-1.jpg"],
    related: ["tag-zorrito", "tag-conejita"],
  },
  {
    id: "stickers-feliz-dia",
    slug: "stickers-feliz-dia-x24",
    name: "Stickers Feliz Día x 24 u.",
    category: "stickers",
    categoryLabel: "Stickers y Washi Tapes",
    occasion: ["cumpleanos"],
    pack: "Pack x 24 unidades",
    price: 3500,
    stock: "in_stock",
    badges: ["new"],
    personalizable: true,
    measures: "4 x 4 cm aprox.",
    material: "Autoadhesivo brillante de 115 g",
    finish: "Impresión digital, terminación brillante",
    productionTime: "3 a 5 días hábiles",
    minQty: 24,
    description: "24 etiquetas “¡Feliz Día!”, personalizadas con tu cuenta de Instagram, marca o nombre. Impresas en autoadhesivo brillante de 115 g.",
    customFields: ["Cuenta de Instagram", "Marca o nombre"],
    images: ["assets/productos/stickers-feliz-dia-1.jpg", "assets/productos/stickers-feliz-dia-2.jpg"],
    related: ["stk-superheroes", "washi-01"],
  },
  {
    id: "super-cierra-todo",
    slug: "super-cierra-todo-x16",
    name: "Super Cierra Todo x 16 u.",
    category: "papeleria-reposteria",
    categoryLabel: "Para repostería",
    occasion: ["cumpleanos"],
    pack: "Pack x 16 unidades",
    price: 3500,
    stock: "in_stock",
    badges: ["new"],
    personalizable: false,
    measures: "12 x 4,5 cm aprox.",
    material: "Autoadhesivo brillante de 115 g",
    finish: "Impresión digital, terminación brillante",
    productionTime: "3 a 5 días hábiles",
    minQty: 16,
    description: "16 etiquetas “Súper Cierra Todo” para sellar bolsitas de golosinas o regalitos. Impresas en autoadhesivo brillante de 115 g.",
    images: ["assets/productos/super-cierra-todo-1.jpg", "assets/productos/super-cierra-todo-2.jpg"],
    related: ["washi-01", "stk-superheroes"],
  },
  {
    id: "etq-animales-heroes",
    slug: "etiquetas-animales-super-heroes",
    name: "Etiquetas Animales Súper Héroes x 15 u.",
    category: "etiquetas",
    categoryLabel: "Etiquetas personalizadas",
    occasion: ["cumpleanos"],
    pack: "Pack x 15 unidades",
    price: null,
    priceOnRequest: true,
    stock: "on_request",
    badges: ["new"],
    personalizable: true,
    measures: "Consultar",
    material: "Consultar",
    finish: "Consultar",
    productionTime: "Consultar",
    minQty: 15,
    description: "15 etiquetas “animales súper héroes”, personalizables con tu cuenta de Instagram, marca o nombre. Foto real cargada el 01/08/2026; precio a confirmar — escribinos por WhatsApp.",
    customFields: ["Cuenta de Instagram", "Marca o nombre"],
    images: ["assets/productos/etiquetas-animales-heroes-1.jpg", "assets/productos/etiquetas-animales-heroes-2.jpg"],
    related: ["etq-mini", "etq-maxi"],
  },
];

const LCG_CATEGORIES = [
  { slug: "papeleria-emprendimientos", label: "Para emprendimientos", desc: "Stickers, tags y etiquetas para vestir tu marca.", colorClass: "1" },
  { slug: "papeleria-reposteria", label: "Para repostería", desc: "Etiquetas y tags pensados para tortas y dulces.", colorClass: "2", image: "assets/productos/super-cierra-todo-1.jpg" },
  { slug: "stickers", label: "Stickers y Washi Tapes", desc: "Para packaging, souvenirs y decoración.", colorClass: "3", image: "assets/productos/stickers-superheroes-1.jpg" },
  { slug: "tags", label: "Tags y etiquetas", desc: "Mini tags y tags para regalo con cordón.", colorClass: "4", image: "assets/productos/tag-conejita-1.jpg" },
  { slug: "tarjetas", label: "Tarjetas", desc: "Para regalar dinero, felicitar o dedicar.", colorClass: "1", image: "assets/productos/tarjeton-pandita-1.jpg" },
  { slug: "toppers", label: "Toppers", desc: "A medida para coronar la torta del festejo.", colorClass: "2" },
  { slug: "cumpleanos", label: "Cumpleaños infantiles", desc: "Colección Especial Día del Niño y kits temáticos.", colorClass: "3", image: "assets/productos/maxi-etiquetas-1.jpg" },
  { slug: "colecciones", label: "Colecciones especiales", desc: "Ediciones limitadas y temporadas.", colorClass: "4" },
];

// Utilidad simple para formatear pesos argentinos
function lcgFormatARS(value) {
  return value.toLocaleString("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 });
}

// Una categoría "tiene productos" si algún producto la usa como category
// o la incluye entre sus occasion (p. ej. "cumpleanos" agrupa por ocasión, no por category).
function lcgCategoryHasProducts(slug) {
  return LCG_PRODUCTS.some((p) => p.category === slug || (p.occasion && p.occasion.includes(slug)));
}

// Categorías con al menos un producto cargado — para no mostrar categorías vacías en el inicio.
function lcgCategoriesWithProducts() {
  return LCG_CATEGORIES.filter((c) => lcgCategoryHasProducts(c.slug));
}
